-- DATABASE_SCHEMA.sql
-- PostgreSQL / Supabase Schema for Website Rental Brokerage System

-- 1. Profiles / Users Table (Extends Supabase Auth users)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'owner')),
  status TEXT DEFAULT 'pending' CHECK (status IN ('active', 'inactive', 'pending', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Setup Row Level Security (RLS) for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to profiles"
  ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profile"
  ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Owners Table
CREATE TABLE public.owners (
  id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.owners ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to owners"
  ON public.owners FOR SELECT USING (true);

CREATE POLICY "Allow admins full access to owners"
  ON public.owners FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- 3. Boarding Houses Table
CREATE TABLE public.boarding_houses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID NOT NULL REFERENCES public.owners(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  description TEXT,
  rules TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.boarding_houses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to boarding_houses"
  ON public.boarding_houses FOR SELECT USING (true);

CREATE POLICY "Allow owners to manage their own boarding houses"
  ON public.boarding_houses FOR ALL USING (
    auth.uid() = owner_id OR
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- 4. Boarding House Images Table
CREATE TABLE public.boarding_house_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  boarding_house_id BIGINT NOT NULL REFERENCES public.boarding_houses(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  image_type TEXT NOT NULL CHECK (image_type IN ('front', 'parking', 'hallway', 'shared_area', 'other')),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.boarding_house_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to approved boarding house images"
  ON public.boarding_house_images FOR SELECT USING (
    status = 'approved' OR
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.id = (
        SELECT owner_id FROM public.boarding_houses WHERE id = boarding_house_id
      ))
    )
  );

CREATE POLICY "Allow owners and admins to manage boarding house images"
  ON public.boarding_house_images FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.id = (
        SELECT owner_id FROM public.boarding_houses WHERE id = boarding_house_id
      ))
    )
  );

-- 5. Room Types Table
CREATE TABLE public.room_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  boarding_house_id BIGINT NOT NULL REFERENCES public.boarding_houses(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price_from NUMERIC NOT NULL,
  area NUMERIC NOT NULL,
  max_people INTEGER DEFAULT 2,
  description TEXT,
  utilities TEXT[] DEFAULT '{}',
  video_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.room_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to room_types"
  ON public.room_types FOR SELECT USING (true);

CREATE POLICY "Allow owners and admins to manage room_types"
  ON public.room_types FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.id = (
        SELECT owner_id FROM public.boarding_houses WHERE id = boarding_house_id
      ))
    )
  );

-- 6. Room Type Images Table
CREATE TABLE public.room_type_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_type_id BIGINT NOT NULL REFERENCES public.room_types(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  image_type TEXT NOT NULL CHECK (image_type IN ('main', 'bedroom', 'bathroom', 'balcony', 'kitchen', 'other')),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.room_type_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to approved room type images"
  ON public.room_type_images FOR SELECT USING (
    status = 'approved' OR
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.id = (
        SELECT owner_id FROM public.boarding_houses WHERE id = (
          SELECT boarding_house_id FROM public.room_types WHERE id = room_type_id
        )
      ))
    )
  );

CREATE POLICY "Allow owners and admins to manage room type images"
  ON public.room_type_images FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND (profiles.role = 'admin' OR profiles.id = (
        SELECT owner_id FROM public.boarding_houses WHERE id = (
          SELECT boarding_house_id FROM public.room_types WHERE id = room_type_id
        )
      ))
    )
  );

-- 7. Leads Table (Customer Inquiry)
CREATE TABLE public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  room_type_id BIGINT NOT NULL REFERENCES public.room_types(id) ON DELETE CASCADE,
  message TEXT,
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'lost', 'won')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anyone to create leads"
  ON public.leads FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow admins to read/update leads"
  ON public.leads FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- 8. Appointments Table (Viewings)
CREATE TABLE public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  appointment_time TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled')),
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow admins full access to appointments"
  ON public.appointments FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );
